"""
Auto-generated by build_exe.py — do not edit by hand.
Source: .env.example
"""

EMBEDDED_ENV = {
    "EML2PST_ADAPTIVE_RATE": "1",
    "EML2PST_ASYNC_IO": "1",
    "EML2PST_CHECKPOINT_EVERY": "1000",
    "EML2PST_COM_PIPELINE": "1",
    "EML2PST_COM_RETRIES": "3",
    "EML2PST_CSV_BOM": "1",
    "EML2PST_DEDUP_BACKEND": "sqlite",
    "EML2PST_GC_EVERY": "500",
    "EML2PST_MMAP_THRESHOLD_MB": "4",
    "EML2PST_OUTLOOK_WAIT_MAX": "3600",
    "EML2PST_PARALLEL_WORKERS": "4",
    "EML2PST_VALIDATE_IMPORT": "1",
}
