"""
Load Mail Exporter settings from embedded defaults and .env files.

Priority (highest first — never overrides keys already in os.environ):
  1. Windows / user environment variables (set before launch)
  2. ``.env`` or ``mail_exporter.env`` next to the .exe or script
  3. ``embedded_env.EMBEDDED_ENV`` baked in at build time (from .env during build_exe.py)
"""

from __future__ import annotations

import logging
import os
import sys
logger = logging.getLogger(__name__)

ENV_PREFIX = "EML2PST_"
ENV_FILENAMES = (".env", "mail_exporter.env")


def is_frozen() -> bool:
    return bool(getattr(sys, "frozen", False))


def app_base_dir() -> str:
    """Directory containing MailExporter.exe or this source tree."""
    if is_frozen():
        return os.path.dirname(os.path.abspath(sys.executable))
    return os.path.dirname(os.path.abspath(__file__))


def _meipass_dir() -> str | None:
    base = getattr(sys, "_MEIPASS", None)
    return base if base and os.path.isdir(base) else None


def env_file_candidates() -> list[str]:
    """Paths to try for an external .env (later entries are lower priority)."""
    dirs: list[str] = []
    meipass = _meipass_dir()
    if meipass:
        dirs.append(meipass)
    dirs.append(app_base_dir())
    paths: list[str] = []
    for directory in dirs:
        for name in ENV_FILENAMES:
            paths.append(os.path.join(directory, name))
    return paths


def parse_dotenv(path: str) -> dict[str, str]:
    """Minimal .env parser (KEY=VALUE, # comments, optional quotes)."""
    result: dict[str, str] = {}
    try:
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError:
        return result
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.lower().startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        result[key] = value
    return result


def _filter_mail_exporter_keys(mapping: dict[str, str]) -> dict[str, str]:
    return {k: v for k, v in mapping.items() if k.startswith(ENV_PREFIX)}


def apply_env_mapping(
    mapping: dict[str, str],
    *,
    override: bool = False,
) -> list[str]:
    """
    Apply keys into os.environ. Returns list of keys that were set.
    By default only sets variables not already present.
    """
    applied: list[str] = []
    for key, value in mapping.items():
        if not key.startswith(ENV_PREFIX):
            continue
        if not override and key in os.environ:
            continue
        os.environ[key] = value
        applied.append(key)
    return applied


def embedded_defaults() -> dict[str, str]:
    try:
        from embedded_env import EMBEDDED_ENV
    except ImportError:
        return {}
    if not isinstance(EMBEDDED_ENV, dict):
        return {}
    return _filter_mail_exporter_keys({str(k): str(v) for k, v in EMBEDDED_ENV.items()})


def load_mail_exporter_env(*, log: bool = True) -> str | None:
    """
    Load embedded + file .env settings. Call once before other modules read os.environ.
    Returns the external .env path used, or None.

    Priority: OS environment > .env beside exe > embedded build defaults.
    """
    embedded = embedded_defaults()
    apply_env_mapping(embedded, override=False)
    embedded_keys = set(embedded)

    loaded_path: str | None = None
    for path in env_file_candidates():
        if not os.path.isfile(path):
            continue
        file_vars = _filter_mail_exporter_keys(parse_dotenv(path))
        if not file_vars:
            continue
        for key, value in file_vars.items():
            if key in os.environ and key not in embedded_keys:
                continue
            os.environ[key] = value
        loaded_path = path
        break

    if log and logger.isEnabledFor(logging.DEBUG):
        logger.debug(
            "Env: embedded=%d keys, file=%s",
            len(embedded_defaults()),
            loaded_path or "(none)",
        )
    return loaded_path


def generate_embedded_env_py(
    env_path: str,
    out_path: str,
    *,
    source_label: str | None = None,
) -> bool:
    """Write embedded_env.py from a .env file (build_exe.py)."""
    if not os.path.isfile(env_path):
        return False
    mapping = _filter_mail_exporter_keys(parse_dotenv(env_path))
    label = source_label or os.path.basename(env_path)
    lines = [
        '"""',
        "Auto-generated by build_exe.py — do not edit by hand.",
        f"Source: {label}",
        '"""',
        "",
        "EMBEDDED_ENV = {",
    ]
    for key in sorted(mapping):
        val = mapping[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{key}": "{val}",')
    lines.append("}")
    lines.append("")
    content = "\n".join(lines)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    return True


def copy_env_beside_exe(exe_path: str, env_path: str) -> str | None:
    """Copy .env next to built executable for easy editing on the VM."""
    if not os.path.isfile(env_path) or not os.path.isfile(exe_path):
        return None
    dest = os.path.join(os.path.dirname(os.path.abspath(exe_path)), ".env")
    try:
        shutil_copy(env_path, dest)
        return dest
    except OSError:
        return None


def shutil_copy(src: str, dest: str) -> None:
    import shutil

    shutil.copy2(src, dest)
